Load pretrained model

In [1]:
import torch
import timm
m = timm.create_model('resnet50', pretrained=True, num_classes=0)
m.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (act1): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act1): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act2): ReLU(inplace=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (act3): ReLU(inplace=True)
      (downsample): Sequen

In [14]:
import numpy as np

random_inputs = torch.randn(4, 3, 250, 250)
random_outputs = m(random_inputs)
cos = torch.nn.CosineSimilarity(dim=1, eps=1e-6)
for output in random_outputs:
    print(cos(output, random_outputs))
#     print(torch.matmul(output, random_outputs.T))

tensor([1.0000, 0.9783, 0.9797, 0.9896], grad_fn=<DivBackward0>)
tensor([0.9783, 1.0000, 0.9752, 0.9778], grad_fn=<DivBackward0>)
tensor([0.9797, 0.9752, 1.0000, 0.9759], grad_fn=<DivBackward0>)
tensor([0.9896, 0.9778, 0.9759, 1.0000], grad_fn=<DivBackward0>)
